version: "3.8"

services:
  shinyproxy:
    image: shinyproxy-example
    container_name: sp-example-container
    # forcing the openanalytics/shinyproxy container to run as root: this works but is not the intent!
    user: 0:0
    build: 
      context: .
      dockerfile: sp.dockerfile
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./shinyproxy/logs:/opt/shinyproxy/logs
    networks:
      - sp-example-net

networks:
  sp-example-net:
    name: sp-example-net
    